type Vector = [number, number];

export type N8nNode = {
  id: string;
  name: string;
  type: string;
  typeVersion: number;
  position: Vector;
  parameters: Record<string, any>;
  notes?: string;
};

export type N8nConnections = Record<string, {
  main: Array<Array<{ node: string; type: "main"; index: number }>>;
}>;

export type N8nWorkflow = {
  name: string;
  nodes: N8nNode[];
  connections: N8nConnections;
};

const randId = () => Math.random().toString(36).slice(2, 10);

function detectUrls(text: string): string[] {
  const urls = text.match(/https?:\/\/[^\s"'<>]+/gi) || [];
  return Array.from(new Set(urls));
}

function contains(text: string, ...terms: string[]): boolean {
  return terms.some((t) => text.includes(t));
}

function createBaseNode(name: string, type: string, x: number, y: number, parameters: Record<string, any> = {}, typeVersion = 1): N8nNode {
  return {
    id: randId(),
    name,
    type,
    typeVersion,
    position: [x, y],
    parameters,
  };
}

export function generateWorkflowFromPrompt(originalPrompt: string, workflowName: string): N8nWorkflow {
  const prompt = originalPrompt.trim();
  const lc = prompt.toLowerCase();
  const urls = detectUrls(prompt);

  const nodes: N8nNode[] = [];
  const connections: N8nConnections = {};

  let cursorX = 240;
  const baseY = 300;
  const advance = () => { cursorX += 220; };

  // Choose trigger
  if (contains(lc, "webhook")) {
    const trigger = createBaseNode("Webhook", "n8n-nodes-base.webhook", cursorX, baseY, {
      path: "incoming",
      responseMode: "responseNode",
    });
    nodes.push(trigger);
    connections[trigger.name] = { main: [[]] };
    advance();
  } else if (contains(lc, "cron", "schedule", "every", "minute", "hour")) {
    const cron = createBaseNode("Cron", "n8n-nodes-base.cron", cursorX, baseY, {
      triggerTimes: { item: [ { mode: "everyMinute" } ] },
    });
    nodes.push(cron);
    connections[cron.name] = { main: [[]] };
    advance();
  } else {
    const start = createBaseNode("Start", "n8n-nodes-base.start", cursorX, baseY);
    nodes.push(start);
    connections[start.name] = { main: [[]] };
    advance();
  }

  // HTTP Request
  if (contains(lc, "http", "request", "fetch", "call", "api") || urls.length) {
    const url = urls[0] ?? "https://api.example.com";
    const http = createBaseNode("HTTP Request", "n8n-nodes-base.httpRequest", cursorX, baseY, {
      url,
      method: "GET",
      responseFormat: "json",
    }, 3);
    nodes.push(http);
    connections[http.name] = { main: [[]] };
    advance();
  }

  // Set
  if (contains(lc, "set", "map", "assign", "add field", "rename")) {
    const set = createBaseNode("Set", "n8n-nodes-base.set", cursorX, baseY, {
      keepOnlySet: false,
      values: { string: [ { name: "note", value: "Generated by n8n-json-generator" } ] },
    }, 2);
    nodes.push(set);
    connections[set.name] = { main: [[]] };
    advance();
  }

  // Code / Function (JS)
  if (contains(lc, "code", "transform", "script", "function")) {
    const code = createBaseNode("Code", "n8n-nodes-base.code", cursorX, baseY, {
      language: "javaScript",
      jsCode: `// Access input data via items\nreturn items.map(item => ({ ...item, json: { ...item.json, transformed: true } }));`,
    }, 1);
    nodes.push(code);
    connections[code.name] = { main: [[]] };
    advance();
  }

  // If condition
  let addedIf = false;
  if (contains(lc, "if", "condition", "when", "status is", "greater than", "less than", "equals")) {
    const ifNode = createBaseNode("If", "n8n-nodes-base.if", cursorX, baseY, {
      conditions: {
        number: [ { value1: "={{$json[\"status\"] || $json[\"statusCode\"] || 200}}", operation: "equal", value2: 200 } ],
      },
    }, 2);
    nodes.push(ifNode);
    connections[ifNode.name] = { main: [[], []] }; // [true],[false]
    addedIf = true;
    advance();
  }

  // Email send
  if (contains(lc, "email")) {
    const email = createBaseNode("Email Send", "n8n-nodes-base.emailSend", cursorX, baseY, {
      toEmail: "you@example.com",
      subject: "Workflow Notification",
      text: "This is a placeholder email. Configure credentials in n8n.",
    }, 2);
    nodes.push(email);
    connections[email.name] = { main: [[]] };
    advance();
  }

  // Slack
  if (contains(lc, "slack")) {
    const slack = createBaseNode("Slack", "n8n-nodes-base.slack", cursorX, baseY, {
      resource: "message",
      operation: "post",
      channel: "#general",
      text: "Hello from generated workflow",
    }, 1);
    nodes.push(slack);
    connections[slack.name] = { main: [[]] };
    advance();
  }

  // Respond to Webhook
  if (contains(lc, "respond", "response", "reply") && nodes.find(n => n.type === "n8n-nodes-base.webhook")) {
    const respond = createBaseNode("Respond to Webhook", "n8n-nodes-base.respondToWebhook", cursorX, baseY, {
      responseBody: "={{$json}}",
      responseCode: 200,
      responseData: "allEntries",
      options: { responseHeaders: { parameters: [] } },
    }, 1);
    nodes.push(respond);
    connections[respond.name] = { main: [[]] };
    advance();
  }

  // Ensure at least Start -> Set pipeline if nothing else
  if (nodes.length === 1) {
    const set = createBaseNode("Set", "n8n-nodes-base.set", cursorX, baseY, {
      keepOnlySet: false,
      values: { string: [ { name: "hello", value: "world" } ] },
    }, 2);
    nodes.push(set);
    connections[set.name] = { main: [[]] };
  }

  // Connect nodes linearly; if there's an If, route true branch to next
  for (let i = 0; i < nodes.length - 1; i++) {
    const from = nodes[i];
    const to = nodes[i + 1];
    const conn = connections[from.name] ?? { main: [[]] };
    if (from.type === "n8n-nodes-base.if") {
      // connect true branch (index 0)
      conn.main[0].push({ node: to.name, type: "main", index: 0 });
      // keep false branch empty
    } else {
      conn.main[0].push({ node: to.name, type: "main", index: 0 });
    }
    connections[from.name] = conn;
  }

  return {
    name: workflowName || "Generated Workflow",
    nodes,
    connections,
  };
}
